<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Members Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            color: #333;
        }
        .header p {
            margin: 5px 0 0 0;
            color: #666;
        }
        .summary {
            background-color: #f8f9fa;
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f8f9fa;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .no-data {
            text-align: center;
            padding: 40px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Members Report</h1>
        <p>Generated on {{ date('F d, Y \a\t H:i A') }}</p>
    </div>

    <div class="summary">
        <strong>Total Members: {{ $members->count() }}</strong>
    </div>

    @if($members->count() > 0)
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Mobile</th>
                <th>Unique ID</th>
                <th>OSWF ID</th>
                <th>Status</th>
                <th>Designation</th>
                <th>Branch</th>
                <th>Join Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($members as $member)
            <tr>
                <td>{{ $member->id }}</td>
                <td>{{ $member->name }}</td>
                <td>{{ $member->email }}</td>
                <td>{{ $member->mobile }}</td>
                <td>{{ $member->unique_id }}</td>
                <td>{{ $member->oswf_id ?? '—' }}</td>
                <td>
                    @if($member->status instanceof \App\Enums\MemberStatus)
                        {{ $member->status->label() }}
                    @else
                        {{ $member->status ?? 'N/A' }}
                    @endif
                </td>
                <td>{{ $member->designation ? $member->designation->designation_name : 'N/A' }}</td>
                <td>{{ $member->branch ? $member->branch->branch_name : 'N/A' }}</td>
                <td>{{ $member->date_of_join_in_ibbl ? $member->date_of_join_in_ibbl->format('M d, Y') : 'N/A' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @else
    <div class="no-data">
        <h3>No members found</h3>
        <p>No members match the current filter criteria.</p>
    </div>
    @endif

    <div class="footer">
        <p>This report was generated by Officer Staff Welfare Foundation System</p>
    </div>
</body>
</html>
