<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Student List Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 0;
            padding: 20px;
        }
        
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        
        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #333;
        }
        
        .header p {
            margin: 5px 0 0 0;
            font-size: 14px;
            color: #666;
        }
        
        .report-info {
            margin-bottom: 20px;
            font-size: 11px;
            color: #666;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        
        th, td {
            border: 1px solid #333;
            padding: 8px;
            text-align: left;
            vertical-align: top;
        }
        
        th {
            background-color: #f5f5f5;
            font-weight: bold;
            font-size: 11px;
        }
        
        td {
            font-size: 10px;
        }
        
        .text-center {
            text-align: center;
        }
        
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ccc;
            padding-top: 10px;
        }
        
        .no-data {
            text-align: center;
            padding: 20px;
            font-style: italic;
            color: #666;
        }
        
        .page-break {
            page-break-before: always;
        }
        
        .summary {
            margin-bottom: 20px;
            padding: 10px;
            background-color: #f8f9fa;
            border: 1px solid #dee2e6;
            border-radius: 4px;
        }
        
        .summary h3 {
            margin: 0 0 10px 0;
            font-size: 14px;
            color: #333;
        }
        
        .summary p {
            margin: 5px 0;
            font-size: 11px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Student List Report</h1>
        <p>Generated on: {{ date('F d, Y \a\t h:i A') }}</p>
    </div>
    
    <div class="summary">
        <h3>Report Summary</h3>
        <p><strong>Total Students:</strong> {{ $students->count() }}</p>
        <p><strong>Report Date:</strong> {{ date('F d, Y') }}</p>
        <p><strong>Generated By:</strong> {{ auth()->user()->name ?? 'System' }}</p>
        
        @if(isset($filters) && (isset($filters['academic_year_id']) || isset($filters['semester_id']) || isset($filters['technology_id'])))
            <h4>Applied Filters:</h4>
            @if(isset($filters['academic_year_id']) && $filters['academic_year_id'])
                @php $academicYear = $academicYears->find($filters['academic_year_id']); @endphp
                <p><strong>Academic Year:</strong> {{ $academicYear->academic_year_name ?? 'N/A' }}</p>
            @endif
            @if(isset($filters['semester_id']) && $filters['semester_id'])
                @php $semester = $semesters->find($filters['semester_id']); @endphp
                <p><strong>Semester:</strong> {{ $semester->semester_name ?? 'N/A' }}</p>
            @endif
            @if(isset($filters['technology_id']) && $filters['technology_id'])
                @php $technology = $technologies->find($filters['technology_id']); @endphp
                <p><strong>Technology:</strong> {{ $technology->technology_name ?? 'N/A' }}</p>
            @endif
        @else
            <p><strong>Filters:</strong> All students (no filters applied)</p>
        @endif
        
        @if($students->count() > 0)
            @php
                $academicYearsGrouped = $students->groupBy('academic_year_id');
                $technologiesGrouped = $students->groupBy('technology_id');
            @endphp
            <p><strong>Academic Years in Report:</strong> {{ $academicYearsGrouped->count() }} different year(s)</p>
            <p><strong>Technologies in Report:</strong> {{ $technologiesGrouped->count() }} different technology(s)</p>
        @endif
    </div>
    
    @if($students->count() > 0)
        <table>
            <thead>
                <tr>
                    <th style="width: 5%;">#</th>
                    <th style="width: 12%;">Student ID</th>
                    <th style="width: 20%;">Student Name</th>
                    <th style="width: 12%;">Student Picture</th>
                    <th style="width: 12%;">Academic Year</th>
                    <th style="width: 10%;">Semester</th>
                    <th style="width: 15%;">Technology</th>
                    <th style="width: 15%;">Email</th>
                    <th style="width: 11%;">Student Phone</th>
                </tr>
            </thead>
            <tbody>
                @foreach($students as $index => $student)
                    <tr>
                        <td class="text-center">{{ $index + 1 }}</td>
                        <td>{{ $student->student_unique_id }}</td>
                        <td>{{ $student->full_name_in_english_block_letter }}</td>
                        <td> @if($student->picture)
                  <img src="{{ asset('images/pictures/' . $student->picture) }}" 
                       alt="{{ $student->full_name_in_english_block_letter }}" 
                       class="rounded-circle" width="40" height="40">
                @else
                  <img src="{{ asset('images/students/default.png') }}" 
                       alt="default" class="rounded-circle" width="40" height="40">
                @endif</td>
                        <td>{{ $student->academicYear->academic_year_name ?? 'N/A' }}</td>
                        <td>{{ $student->semester->semester_name ?? 'N/A' }}</td>
                        <td>{{ $student->technology->technology_name ?? 'N/A' }}</td>
                        <td>{{ $student->email ?? 'N/A' }}</td>
                        <td>{{ $student->personal_number ?? 'N/A' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="no-data">
            <p>No students found matching the criteria.</p>
        </div>
    @endif
    
    <div class="footer">
        <p>This report was generated automatically by the Polytechnic Management System</p>
        <p>For any queries, please contact the administration office</p>
    </div>
</body>
</html>
