<?php
// Variables
return [
  "creatorName" => "Bijoy LAB",
  "creatorUrl" => "https://bijoylab.com",
  "templateName" => "PPI",
  "templateSuffix" => "",
  "templateVersion" => "2.0.0",
  "templateFree" => false,
  "templateDescription" => "Start your development with a Dashboard for Bootstrap 5",
  "templateKeyword" => "dashboard, bootstrap 5 dashboard, bootstrap 5 design, bootstrap 5",
  "licenseUrl" => "",
  "livePreview" => "",
  "productPage" => "https://bijoylab.com",
  "support" => "https://bijoylab.com",
  "moreThemes" => "",
  "documentation" => "",
  "generator" => "",
  "changelog" => "",
  "repository" => "",
  "gitRepo" => "",
  "gitRepoAccess" => "",
  "githubFreeUrl" => "",
  "facebookUrl" => "",
  "twitterUrl" => "",
  "githubUrl" => "",
  "dribbbleUrl" => "",
  "instagramUrl" => "",
];
