<!DOCTYPE html>
<html>
<head>
    <title>Investment Collections Report</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .header { text-align: center; margin-bottom: 30px; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: right; font-size: 10px; }
        .summary { margin-top: 20px; text-align: right; }
    </style>
</head>
<body>
    <div class="header">
        <h2>Investment Collection Report</h2>
        <p>Generated on: {{ date('M d, Y H:i A') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Receipt #</th>
                <th>Account #</th>
                <th>Member</th>
                <th>Inst #</th>
                <th>Net Amount</th>
                <th>Method</th>
            </tr>
        </thead>
        <tbody>
            @php $total = 0; @endphp
            @foreach($collections as $item)
                @php 
                    $net = $item->total_amount - ($item->discount_amount ?? 0);
                    $total += $net;
                @endphp
                <tr>
                    <td>{{ $item->paid_date->format('Y-m-d') }}</td>
                    <td>{{ $item->receipt_number }}</td>
                    <td>{{ $item->investment->account->account_number ?? 'N/A' }}</td>
                    <td>{{ $item->investment->member->name }}</td>
                    <td>#{{ $item->installment_number }}</td>
                    <td>${{ number_format($net, 2) }}</td>
                    <td>{{ $item->paymentMethod->payment_method_name ?? 'N/A' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="summary">
        <h3>Total Collected: ${{ number_format($total, 2) }}</h3>
    </div>

    <div class="footer">
        Page generated by OSWF System
    </div>
</body>
</html>

