<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Students List Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 10px;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            color: #333;
        }
        .header p {
            margin: 5px 0 0 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 4px;
            text-align: left;
            font-size: 9px;
        }
        th {
            background-color: #f5f5f5;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .summary {
            margin-top: 20px;
            padding: 10px;
            background-color: #f0f0f0;
            border-radius: 5px;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 8px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Students List Report</h1>
        <p>Generated on: {{ date('Y-m-d H:i:s') }}</p>
        <p>Total Students: {{ $students->count() }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Student Name</th>
                <th>Student ID</th>
                <th>Father's Name</th>
                <th>Mother's Name</th>
                <th>Phone</th>
                <th>Academic Year</th>
                <th>Semester</th>
                <th>Technology</th>
                <th>Shift</th>
                <th>Date of Birth</th>
            </tr>
        </thead>
        <tbody>
            @foreach($students as $index => $student)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $student->full_name_in_english_block_letter ?? 'N/A' }}</td>
                    <td>{{ $student->student_unique_id ?? 'N/A' }}</td>
                    <td>{{ $student->father_name_in_english_block_letter ?? 'N/A' }}</td>
                    <td>{{ $student->mother_name_in_english_block_letter ?? 'N/A' }}</td>
                    <td>{{ $student->personal_number ?? 'N/A' }}</td>
                    <td>{{ $student->academicYear->academic_year_name ?? 'N/A' }}</td>
                    <td>{{ $student->semester->semester_name ?? 'N/A' }}</td>
                    <td>{{ $student->technology->technology_name ?? 'N/A' }}</td>
                    <td>{{ $student->shift->shift_name ?? 'N/A' }}</td>
                    <td>{{ $student->date_of_birth ? \Carbon\Carbon::parse($student->date_of_birth)->format('Y-m-d') : 'N/A' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="summary">
        <strong>Report Summary:</strong><br>
        Total Students: {{ $students->count() }}<br>
        Generated on: {{ date('Y-m-d H:i:s') }}<br>
        Report generated by: Polytechnic Management System
    </div>

    <div class="footer">
        <p>This is a computer generated report. No signature required.</p>
    </div>
</body>
</html>
