<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Expenses Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            color: #333;
        }
        .header p {
            margin: 5px 0 0 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f5f5f5;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .amount {
            text-align: right;
        }
        .summary {
            margin-top: 20px;
            padding: 10px;
            background-color: #f0f0f0;
            border-radius: 5px;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Expenses Report</h1>
        <p>Generated on: {{ date('Y-m-d H:i:s') }}</p>
        <p>Total Expenses: {{ $expenses->count() }}</p>
        <p>Total Amount: {{ number_format($expenses->sum('amount'), 2) }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Expense Head</th>
                <th>Expense Date</th>
                <th>Amount</th>
                <th>Remarks</th>
            </tr>
        </thead>
        <tbody>
            @foreach($expenses as $index => $expense)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $expense->expenseHead->name ?? 'N/A' }}</td>
                    <td>{{ $expense->expense_date ? \Carbon\Carbon::parse($expense->expense_date)->format('M d, Y') : 'N/A' }}</td>
                    <td class="amount">{{ number_format($expense->amount, 2) }}</td>
                    <td>{{ $expense->remarks ?? 'N/A' }}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr style="background-color: #e9ecef; font-weight: bold;">
                <td colspan="3">Total</td>
                <td class="amount">{{ number_format($expenses->sum('amount'), 2) }}</td>
                <td></td>
            </tr>
        </tfoot>
    </table>

    <div class="summary">
        <strong>Report Summary:</strong><br>
        Total Expenses: {{ $expenses->count() }}<br>
        Total Amount: {{ number_format($expenses->sum('amount'), 2) }}<br>
        Generated on: {{ date('Y-m-d H:i:s') }}<br>
        Report generated by: Polytechnic Management System
    </div>

    <div class="footer">
        <p>This is a computer generated report. No signature required.</p>
    </div>
</body>
</html>
