<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Teachers List Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            color: #333;
        }
        .header p {
            margin: 5px 0 0 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f5f5f5;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .summary {
            margin-top: 20px;
            padding: 10px;
            background-color: #f0f0f0;
            border-radius: 5px;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Teachers List Report</h1>
        <p>Generated on: {{ date('Y-m-d H:i:s') }}</p>
        <p>Total Teachers: {{ $teachers->count() }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Teacher Name</th>
                <th>Teacher ID</th>
                <th>Designation</th>
                <th>Email</th>
                <th>Mobile</th>
                <th>Gender</th>
                <th>Joining Date</th>
                <th>Basic Salary</th>
                <th>Gross Salary</th>
            </tr>
        </thead>
        <tbody>
            @foreach($teachers as $index => $teacher)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $teacher->teacher_name }}</td>
                    <td>{{ $teacher->teacher_unique_id ?? 'N/A' }}</td>
                    <td>{{ $teacher->designation->designation_name ?? 'N/A' }}</td>
                    <td>{{ $teacher->email ?? 'N/A' }}</td>
                    <td>{{ $teacher->mobile ?? 'N/A' }}</td>
                    <td>{{ $teacher->gender ?? 'N/A' }}</td>
                    <td>{{ $teacher->joining_date ? \Carbon\Carbon::parse($teacher->joining_date)->format('Y-m-d') : 'N/A' }}</td>
                    <td>{{ $teacher->basic_salary ?? 'N/A' }}</td>
                    <td>{{ $teacher->gross_salary ?? 'N/A' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="summary">
        <strong>Report Summary:</strong><br>
        Total Teachers: {{ $teachers->count() }}<br>
        Generated on: {{ date('Y-m-d H:i:s') }}<br>
        Report generated by: Polytechnic Management System
    </div>

    <div class="footer">
        <p>This is a computer generated report. No signature required.</p>
    </div>
</body>
</html>
